### ISSUE TITLE
Mute Command Fails to Parse Units of Time

### ISSUE THREAD

**Issue by amnotbananaama** [yitzy299/server-simplified#1] opened 2020-11-28 20:36 UTC
The `/mute` command seems to have problems with processing the units of time argument.

### Steps to Reproduce
1. Start a dedicated 1.16.4 server with `fabric-api-0.26.3+1.16.jar` and `server-simplified-1.0.3.jar`.
2. Give yourself permission to use the `/mute` command (either `/op <username>` or `/permission <username> add mute`).
3. Attempt to mute any player for a duration of time (`/mute @s 3m`)
-> ❌ "Failed to parse time. Input must be numerical!"

### Analysis 
By adding a debugging statement [here](https://github.com/yitzy299/server-simplified/blob/a7abc0b/src/main/java/tech/dttp/serversimplified/commands/MuteCommand.java#L71):
`System.out.println(time.toString());` We can see that the value of `time.toString()` is:
```
[STDOUT]: TextComponent{text='3m', siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}
```
I'm not really sure where to go from here, still learning Java but I hope that's enough! 😅

**Comment by yitzy299** [comment] 2020-11-28 20:57
I was aware, thanks for raising. I believe the issue is somewhere it converts the entire `Text` to a String, rather than getting the value of the text as a String

**Comment by yitzy299** [comment] 2020-11-28 21:30
Fixed in the latest commit

**Closed by yitzy299** 2020-11-28 21:30 UTC
